newsbot/urls.py
from django.urls import path, re_path

from . import views
from myApp.views import *

app_name='newsbot'

urlpatterns = [
    path('', views.index, name='index'),
    path('newsbot/', views.index, name='index'),
    path('load-data/', myView, name='myView'),
    path('dict-builder/', dictBuilder, name='dictBuilder'),
    path('some-more-data/', someMoreData, name='someMoreData'),
    path('some-more-articles/', moreArticles, name='moreArticles'),
]

newsbot/models.py
from django.db import models


class ArticleExample(models.Model):
    # This will hold the visible text for this example
    body_text = models.TextField()
    # This bias score is a left-right bias provided by Media Bias Chart, but not used in this project.
    bias_score = models.FloatField()
    bias_class = models.IntegerField()
    # quality_score comes from the Media Bias Chart data
    quality_score = models.FloatField()
    # quality_class is based on the bias score and allows us to then integrate politifact data in their
    # 4-class way, True = 4, Mostly True = 3, Mostly Fake = 2, Fake = 1
    quality_class = models.IntegerField()
    
    origin_url = models.TextField()
    origin_source = models.TextField()

class DictEntry(models.Model):
    canonWord = models.TextField()
    
class UserEntry(models.Model):
    entryURL = models.URLField(verbose_name='URL of news article')

    

newsbot/forms.py
# this file isn't needed, I had to create it to get the crispy_tags form, then I modified that to use 
# a GET request to make the final URL shareable

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit, Field, Fieldset

from django.forms import ModelForm, Textarea

from .models import *

class ArticleTesterForm(ModelForm):
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(ArticleTesterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            ButtonHolder(
                Field('entryURL'),
                Submit('submit', 'Analyze', css_class='btn btn-primary')
            )
            )
     
    class Meta:
        model = UserEntry
        exclude = []

newsbot/views.py
from django.shortcuts import render
import pandas as pd
import numpy as np
import pickle
from .models import *
from .forms import *
from newsbot.strainer import *
from newsbot.util import *

def index(request):
    
    url = request.GET.get('u')
    if((url is not None) and (len(url) > 5)):
        # 1. Load the model from disk
        print("Setting up")
        svc_model = pickle.load(open('newsbot/svc_model.sav', 'rb'))
        mlp_model = pickle.load(open('newsbot/MLPC_model.sav', 'rb'))
        log_model = pickle.load(open('newsbot/log_model.sav', 'rb'))
        cDict = loadCanonDict()
        ss = SoupStrainer()
        ss.init()
        print("Setup complete")
        print("Attempting URL: " + url)
        if(ss.loadAddress(url)):
            articleX = buildExampleRow(ss.extractText, cDict)
            print("My Dict,SS: ",cDict,ss.extractText)

            print("My Article: ",articleX)
        else:
            print("Error on URL, exiting")
            return render(request, 'urlFail.html', {'URL', url})

        articleX = articleX.reshape(1, -1)
        print("article", articleX)
        # 5. Send the X row to the model to produce a prediction
        svc_prediction = svc_model.predict(articleX)
        svc_probabilities = svc_model.predict_proba(articleX)
        
        mlp_prediction = mlp_model.predict(articleX)
        mlp_probabilities = mlp_model.predict_proba(articleX)
        
        log_prediction = log_model.predict(articleX)
        log_probabilities = log_model.predict_proba(articleX)
        print(svc_prediction, mlp_prediction, log_prediction)
        # The classifications produced as predictions, espcially by the SVC, are sometimes different
        # than the highest probability. So, we'll calculate fake + dodgy and seems legit + true to come up 
        # with a ruling of yes or no, is it real or not. Then we'll give the probabiilties to allow
        # the user to make up their mind.

        svc_prb = (svc_probabilities[0][0]*100, svc_probabilities[0][1]*100, svc_probabilities[0][2]*100, svc_probabilities[0][3]*100)
        svc_totFake = (svc_probabilities[0][0]*100) + (svc_probabilities[0][1]*100)
        svc_totReal = (svc_probabilities[0][2]*100) + (svc_probabilities[0][3]*100)

        mlp_prb = (mlp_probabilities[0][0]*100, mlp_probabilities[0][1]*100, mlp_probabilities[0][2]*100, mlp_probabilities[0][3]*100)
        mlp_totFake = (mlp_probabilities[0][0]*100) + (mlp_probabilities[0][1]*100)
        mlp_totReal = (mlp_probabilities[0][2]*100) + (mlp_probabilities[0][3]*100)

        log_prb = (log_probabilities[0][0]*100, log_probabilities[0][1]*100, log_probabilities[0][2]*100, log_probabilities[0][3]*100)
        log_totFake = (log_probabilities[0][0]*100) + (log_probabilities[0][1]*100)
        log_totReal = (log_probabilities[0][2]*100) + (log_probabilities[0][3]*100)
        
        fin_prb = ( (((svc_probabilities[0][0]*100)+(mlp_probabilities[0][0]*100)+(log_probabilities[0][0]*100))/3), 
                    (((svc_probabilities[0][1]*100)+(mlp_probabilities[0][1]*100)+(log_probabilities[0][1]*100))/3),
                    (((svc_probabilities[0][2]*100)+(mlp_probabilities[0][2]*100)+(log_probabilities[0][2]*100))/3),
                    (((svc_probabilities[0][3]*100)+(mlp_probabilities[0][3]*100)+(log_probabilities[0][3]*100))/3) )
        fin_totFake = (svc_totFake + mlp_totFake + log_totFake)/3
        fin_totReal = (svc_totReal + mlp_totReal + log_totReal)/3

        # 6. Display the processed text and the results
        
        context = {'headline':ss.recHeadline, 'words': ss.extractText, 'url' : url,
                   'svc_totFake': svc_totFake, 
                   'svc_totReal': svc_totReal, 
                   'svc_prediction': svc_prediction, 
                   'svc_probabilities': svc_prb, 
                   'mlp_totFake': mlp_totFake, 
                   'mlp_totReal': mlp_totReal, 
                   'mlp_prediction': mlp_prediction, 
                   'mlp_probabilities': mlp_prb,
                   'log_totFake': log_totFake, 
                   'log_totReal': log_totReal, 
                   'log_prediction': log_prediction, 
                   'log_probabilities': log_prb,
                   'fin_totFake': fin_totFake, 
                   'fin_totReal': fin_totReal, 
                   'fin_probabilities': fin_prb
                   }

        return render(request, 'newsbot/results.html', context)
    else:
        return render(request, 'newsbot/urlForm.html')
    

templates/newsbot/results.html
{#{% extends 'base/base.html' %}#}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Base</title>
</head>
{% block extrahead %}
	<title>NewsBot Artificial Intelligence for detection of fake news</title>
	<meta property="og:title" content="NewsBot Artificial Intelligence for detection of fake news">
	<meta property="twitter:title" content="NewsBot Artificial Intelligence for detection of fake news">
	<meta property="og:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">
	<meta property="twitter:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">

	<meta property="og:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta property="twitter:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta name="description" content="NewsBot Artificial Intelligence for detection of fake news">
	<meta name="keywords" content="artificial intelligence natural language processing news fake news detection">
	<meta property="og:url" content="https://www.unslanted.net/newsbot/">
	<meta property="twitter:url" content="https://www.unslanted.net/newsbot/">
	<meta property="og:type" content="article">
	<meta property="twitter:type" content="article">
<link rel="canonical" href="https://www.unslanted.net/newsbot/" />
<meta name="twitter:partner" content="unslanted.net">
<meta name="twitter:card" content="summary">
<style>
input[type=url] {
  border: 2px solid blue;
  border-radius: 4px;
}
input[type=submit] {
  border: 2px solid blue;
  border-radius: 4px;
}

</style>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/css/bootstrap-slider.min.css" />
{% endblock %}

{% block content %}
<div class="row row row-fluid">
	<div class="wpb_column columns small-12 medium-12">
		<div class="vc_column-inner  ">
			<div class="wpb_wrapper">

	<h2>Analysis of <a href="{{ url }}">{{ headline }}</a><br><br></h2>

	<a href="/newsbot/"><button class="btn btn-primary btn btn-primary">Analyze another</button></a>


	<h3 style="text-align: center;">
	Combined Result:<br>
	{% if fin_totFake >= fin_totReal %}
		Fake/Dodgy
	{% else %}
		Seems Legit/True
	{% endif %}
	</h3>
	
	<br>

Probability of Fake: {{ fin_probabilities.0|floatformat }}% chance of Fake
<div class="progress">
  <div class="progress-bar" id="fakeProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.0 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.0 }}%"></div>
</div>
	 
	<br>

Probability of Dodgy: {{ fin_probabilities.1|floatformat }}% chance of Dodgy
<div class="progress">
  <div class="progress-bar" id="MfakeProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.1 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.1 }}%"></div>
</div>
	 
	<br>

Probability of Mostly True: {{ fin_probabilities.2|floatformat }}% chance of Mostly True
<div class="progress">
  <div class="progress-bar" id="MtrueProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.2 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.2 }}%"></div>
</div>
	 
	<br>

Probability of True: {{ fin_probabilities.3|floatformat }}% chance of True
<div class="progress">
  <div class="progress-bar" id="trueProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.3 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.3 }}%"></div>
</div>


<br><br><hr><br><br>
	<h2 style="text-align: center;">
	Individual model results
	</h2>


	<h3 style="text-align: center;">
	Support Vector Classifier Result:<br>
	{% if svc_totFake >= svc_totReal %}
		Fake/Dodgy
	{% else %}
		Seems Legit/True
	{% endif %}
	</h3>
	
	<br>

Probability of Fake: {{ svc_probabilities.0|floatformat }}% chance of Fake
<div class="progress">
  <div class="progress-bar" id="fakeProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.0 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.0 }}%"></div>
</div>
	 
	<br>

Probability of Dodgy: {{ svc_probabilities.1|floatformat }}% chance of Dodgy
<div class="progress">
  <div class="progress-bar" id="MfakeProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.1 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.1 }}%"></div>
</div>
	 
	<br>

Probability of Mostly True: {{ svc_probabilities.2|floatformat }}% chance of Mostly True
<div class="progress">
  <div class="progress-bar" id="MtrueProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.2 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.2 }}%"></div>
</div>
	 
	<br>

Probability of True: {{ svc_probabilities.3|floatformat }}% chance of True
<div class="progress">
  <div class="progress-bar" id="trueProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.3 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.3 }}%"></div>
</div>
	 
	<br><hr><br>

	<h3 style="text-align: center;">
	Logistic Regression Result:<br>
	{% if log_totFake >= log_totReal %}
		Fake/Dodgy
	{% else %}
		Seems Legit/True
	{% endif %}
	</h3>
	
	<br>

Probability of Fake: {{ log_probabilities.0|floatformat }}% chance of Fake
<div class="progress">
  <div class="progress-bar" id="fakeProb_bar" role="progressbar" aria-valuenow="{{ log_probabilities.0 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ log_probabilities.0 }}%"></div>
</div>
	 
	<br>

Probability of Dodgy: {{ log_probabilities.1|floatformat }}% chance of Dodgy
<div class="progress">
  <div class="progress-bar" id="MfakeProb_bar" role="progressbar" aria-valuenow="{{ log_probabilities.1 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ log_probabilities.1 }}%"></div>
</div>
	 
	<br>

Probability of Mostly True: {{ log_probabilities.2|floatformat }}% chance of Mostly True
<div class="progress">
  <div class="progress-bar" id="MtrueProb_bar" role="progressbar" aria-valuenow="{{ log_probabilities.2 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ log_probabilities.2 }}%"></div>
</div>
	 
	<br>

Probability of True: {{ log_probabilities.3|floatformat }}% chance of True
<div class="progress">
  <div class="progress-bar" id="trueProb_bar" role="progressbar" aria-valuenow="{{ log_probabilities.3 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ log_probabilities.3 }}%"></div>
</div>
	 
	<br><hr><br>
	
	
	<h3 style="text-align: center;">
	Multilayer Perceptron Result:<br>
	{% if mlp_totFake >= mlp_totReal %}
		Fake/Dodgy
	{% else %}
		Seems Legit/True
	{% endif %}
	</h3>
	
	<br>

Probability of Fake: {{ mlp_probabilities.0|floatformat }}% chance of Fake
<div class="progress">
  <div class="progress-bar" id="fakeProb_bar" role="progressbar" aria-valuenow="{{ mlp_probabilities.0 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ mlp_probabilities.0 }}%"></div>
</div>
	 
	<br>

Probability of Dodgy: {{ mlp_probabilities.1|floatformat }}% chance of Dodgy
<div class="progress">
  <div class="progress-bar" id="MfakeProb_bar" role="progressbar" aria-valuenow="{{ mlp_probabilities.1 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ mlp_probabilities.1 }}%"></div>
</div>
	 
	<br>

Probability of Mostly True: {{ mlp_probabilities.2|floatformat }}% chance of Mostly True
<div class="progress">
  <div class="progress-bar" id="MtrueProb_bar" role="progressbar" aria-valuenow="{{ mlp_probabilities.2 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ mlp_probabilities.2 }}%"></div>
</div>
	 
	<br>

Probability of True: {{ mlp_probabilities.3|floatformat }}% chance of True
<div class="progress">
  <div class="progress-bar" id="trueProb_bar" role="progressbar" aria-valuenow="{{ mlp_probabilities.3 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ mlp_probabilities.3 }}%"></div>
</div>
	

	<hr>
	Extracted words: {{ words }}<br>
<br><br><br>
			</div>
		</div>
	</div>
</div>
{% endblock %}
</html>

templates/newsbot/urlForm.html
{#{% extends 'base/base.html' %}#}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Base</title>
</head>
{% load crispy_forms_tags %}
{% block extrahead %}
	<title>NewsBot Artificial Intelligence for detection of fake news</title>
	<meta property="og:title" content="NewsBot Artificial Intelligence for detection of fake news">
	<meta property="twitter:title" content="NewsBot Artificial Intelligence for detection of fake news">
	<meta property="og:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">
	<meta property="twitter:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">

	<meta property="og:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta property="twitter:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta name="description" content="NewsBot Artificial Intelligence for detection of fake news">
	<meta name="keywords" content="artificial intelligence natural language processing news fake news detection">
	<meta property="og:url" content="https://www.unslanted.net/newsbot/">
	<meta property="twitter:url" content="https://www.unslanted.net/newsbot/">
	<meta property="og:type" content="article">
	<meta property="twitter:type" content="article">
<link rel="canonical" href="https://www.unslanted.net/newsbot/" />
<meta name="twitter:partner" content="unslanted.net">
<meta name="twitter:card" content="summary">
<style>
input[type=url] {
  border: 2px solid blue;
  border-radius: 4px;
}
input[type=submit] {
  border: 2px solid blue;
  border-radius: 4px;
}

</style>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/css/bootstrap-slider.min.css" />
{% endblock %}


{% block content %}
<div class="row row row-fluid">
	<div class="wpb_column columns small-12 medium-12">
		<div class="vc_column-inner  ">
			<div class="wpb_wrapper">

<h2 style="text-align: center;">NewsBot AI: An AI for detecting fake news</h2>

<form  method="get" >
 <div  
    class="buttonHolder"> <div id="div_id_entryURL" class="form-group"> <label for="id_entryURL" class="col-form-label  requiredField">
                URL of news article<span class="asteriskField">*</span> </label> <div class=""> 
                <input type="url" name="u" class="urlinput form-control" maxlength="200" id="id_entryURL" required> </div> </div> <input type="submit"
    name="submit"
    value="Analyze"
    
        class="btn btn-primary btn btn-primary"
        id="submit-id-submit"
    
    
    />

</div> </form>
<h3 style="text-align: center;">Results will take a few seconds to load</h3>

<b>What is this thing?</b><br>
This artificial intelligence can predict whether a news article is fake or real based on the words used in the article.
You can find a detailed documentation of how it works and how it was coded at: 
<a href="medium link">Full Pipeline Project: Python AI for detecting fake news with NLP</a>
<br><br>

<b>What do I do?</b><br>
Enter a URL in the box above, the bot will load the article, extract the visible text, and 
use 3 different AI models to make a prediction of
whether the article is fake or real. This may take several seconds because the URL you enter has
to be loaded and processed.
You will get a probability distrobution and a final ruling. <br><br>

<b>Any article I want?</b><br> 
The model has been trained only on US political news. Anything outside of that domain is unlikely to
produce credible results. 
Bot will not load articles from Bloomberg.com because of their robots.txt policy.<br><br>

<b>I have more questions, comments, and concerns</b>
<a href="mailto:aurelius@unslanted.net">Email me here</a>

<br><br>

<br><br><br>
			</div>
		</div>
	</div>
</div>


{% endblock %}
</html>